/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import static Login.sistemLogin.Arrusers;
import SistemParkirFilkomUB.formParkir;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ahm4d
 */
public class formLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        sistemLogin.inisialisasiData();
        bt_login.setBackground(Color.yellow);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_blue = new javax.swing.JPanel();
        bg_top = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        logojoinub = new javax.swing.JLabel();
        logofilkom = new javax.swing.JLabel();
        bt_exit = new javax.swing.JButton();
        bt_minimaze = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_username = new javax.swing.JLabel();
        in_username = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        in_password = new javax.swing.JPasswordField();
        bt_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Parkir FILKOM-UB");

        bg_blue.setBackground(new java.awt.Color(140, 122, 230));

        bg_top.setBackground(new java.awt.Color(116, 125, 140));

        title.setFont(new java.awt.Font("Open Sans Extrabold", 1, 48)); // NOI18N
        title.setText("Sistem Parkir FILKOM-UB");

        logojoinub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/joinub.png"))); // NOI18N
        logojoinub.setToolTipText("");
        logojoinub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logojoinubMouseClicked(evt);
            }
        });

        logofilkom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filkom.png"))); // NOI18N
        logofilkom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logofilkomMouseClicked(evt);
            }
        });

        bt_exit.setBackground(new java.awt.Color(116, 125, 140));
        bt_exit.setForeground(new java.awt.Color(116, 125, 140));
        bt_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });

        bt_minimaze.setBackground(new java.awt.Color(116, 125, 140));
        bt_minimaze.setForeground(new java.awt.Color(116, 125, 140));
        bt_minimaze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimaze.png"))); // NOI18N
        bt_minimaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_minimazeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_topLayout = new javax.swing.GroupLayout(bg_top);
        bg_top.setLayout(bg_topLayout);
        bg_topLayout.setHorizontalGroup(
            bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_topLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(logojoinub)
                .addGroup(bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_topLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logofilkom)
                        .addContainerGap(204, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_topLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_minimaze, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_topLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(89, 89, 89))
        );
        bg_topLayout.setVerticalGroup(
            bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_topLayout.createSequentialGroup()
                .addGroup(bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_topLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(logofilkom)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_topLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logojoinub)
                            .addComponent(bt_minimaze, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(title))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("© 2020 Sistem Parkir FILKOM UB by Kelompok 5");

        jPanel1.setBackground(new java.awt.Color(66, 233, 245));

        lb_username.setText("username");

        lb_password.setText("password");

        bt_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        bt_login.setText("login");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lb_password))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lb_username))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_password, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in_username, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_login))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_login)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bg_blueLayout = new javax.swing.GroupLayout(bg_blue);
        bg_blue.setLayout(bg_blueLayout);
        bg_blueLayout.setHorizontalGroup(
            bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_blueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_blueLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_blueLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))))
        );
        bg_blueLayout.setVerticalGroup(
            bg_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_blueLayout.createSequentialGroup()
                .addComponent(bg_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        String username = in_username.getText();
        String password = in_password.getText();
        boolean isMasuk = false;
        for (int i = 0; i < Arrusers.size(); i++) {
            if(sistemLogin.Arrusers.get(i).getUname().equals(in_username.getText()) && sistemLogin.Arrusers.get(i).getPass().equals(in_password.getText())){
                isMasuk = true;
            }
        }
        if(isMasuk == true){
            this.setVisible(false);
            formParkir parkirPage = new formParkir();
            parkirPage.setResizable(false);
            parkirPage.setVisible(true);
        }else if (username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "username atau password tidak boleh kosong!", "Peringatan",2);
        }else{
            JOptionPane.showMessageDialog(this, "username atau password salah!", "Peringatan", 2);
        }
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        // TODO add your handling code here:
        int respon = JOptionPane.showConfirmDialog(this, "Apakah anda ingin keluar dari program?", "Keluar Program", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respon == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan program kami!");
            System.exit(0);
        }
    }//GEN-LAST:event_bt_exitActionPerformed

    private void bt_minimazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_minimazeActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_bt_minimazeActionPerformed

    private void logojoinubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logojoinubMouseClicked
        // TODO add your handling code here:
        Desktop browser = Desktop.getDesktop();
        try{
            browser.browse(new URI("http://www.ub.ac.id"));
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_logojoinubMouseClicked

    private void logofilkomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logofilkomMouseClicked
        // TODO add your handling code here:
               Desktop browser = Desktop.getDesktop();
        try{
            browser.browse(new URI("http://www.filkom.ub.ac.id"));
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_logofilkomMouseClicked

    public static void main(String[] args) {
        new formLogin().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_blue;
    private javax.swing.JPanel bg_top;
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_minimaze;
    private javax.swing.JPasswordField in_password;
    private javax.swing.JTextField in_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_username;
    private javax.swing.JLabel logofilkom;
    private javax.swing.JLabel logojoinub;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
